version: '3'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-CU14-ubuntu-20.04
    environment:
      SA_PASSWORD: "sapwdlocal@123"
      ACCEPT_EULA: "Y"
    ports:
      - "10001:1433"
  solr:
    image: solr:7.4
    command: "solr-demo"
    ports:
     - "8983:8983"