name: .NET

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:    
    - name: Set Timezone
      uses: szenius/set-timezone@v1.0
      with:
        timezoneLinux: "Asia/Singapore"
        timezoneMacos: "Asia/Singapore"
        timezoneWindows: "Singapore Standard Time"
    - uses: actions/checkout@v3
    - name: Setup net6.0
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Setup netcoreapp3.1
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build 6
      run: dotnet build --no-restore --configuration Debug
    - name: Test 6
      run: dotnet test Community.Data.OData.Linq.xTests --no-build --verbosity normal --configuration Debug
    - name: Build 3.1
      run: dotnet build --no-restore --configuration Debug
    - name: Test 3.1
      run: dotnet test Community.Data.OData.Linq.xTests --no-build --verbosity normal --configuration Debug
